version: '3.1'

services:
  test-environment:
    build:
      context: ./
      dockerfile: ./Dockerfile.test-environment 
    volumes:
      - ./:/opt/project
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    workdir: /opt/project
